<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ORGANIZATIONNAME</name>
   <tag></tag>
   <elementGuidId>76e38a2c-9fc5-433f-b6d8-3adb008cda09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;CoordinatorReceiptTable&quot;]/tbody/tr/td[1]/div[2]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;CoordinatorReceiptTable&quot;]/tbody/tr/td[1]/div[2]/div[1]</value>
   </webElementXpaths>
</WebElementEntity>
