<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hi_TextProfile</name>
   <tag></tag>
   <elementGuidId>1f4ecee5-5c12-4040-b6be-9a5892bed047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ol//*[(text()='Profile')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
